#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define CLIENT_ID "_client"
#define EXIT_MESSAGE "_"
#define BUFFSIZE 255
#define SERVER_PORT 16000

#define SEM_CLIENTSOCKETS_ARRAY 0
#define SHM_CANT_CLIENTSOCKETS_ARRAY 0
#define NOM_CLIENTSOCKETS_ARRAY "clientsockets_array"

#endif // DEFINES_H_INCLUDED
