#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define CLIENT_ID "_client"
#define EXIT_MESSAGE "_"
#define SEPARATOR "#"
#define BUFFSIZE 255
#define NICKSIZE 20
#define SERVER_PORT 16000

#define NOM_SERVER_SOCKETS "sockets"
#define C_SERVER_SOCKETS 0

#define NOM_SERVER_SENDER "SNDR"
#define C_SENDER_RECIBIDOS 0
#define C_SENDER_ENVIADOS 1

#endif // DEFINES_H_INCLUDED
